### ISSUE TITLE
VHT throws NumberFormatException on class field

### ISSUE THREAD

**Issue by simdugas** [yahoo/samoa#136]
I'm trying to debug the following error, PrequentialEvaluation with VHT (classification) throws a NumberFormatException for the class attribute. Why is it trying to parse the class attribute as an integer? I can't find a format error in my ARFF file. It was created with weka.core.converters.CSVLoader. Other datasets (nominal only) work fine with my install of SAMOA. This configuration runs fine in MOA.

#### Command Line Argument
bin/samoa local target/SAMOA-Local-0.3.0-SNAPSHOT.jar "PrequentialEvaluation -l com.yahoo.labs.samoa.learners.classifiers.trees.VerticalHoeffdingTree -s (ArffFileStream -f test.arff) -f 1"

#### ARFF File
@relation test.txt

@attribute Dur numeric
@attribute Proto {udp,tcp,icmp,arp,ipx/spx,ipv6-icmp,pim,esp,igmp,rtcp,rtp,ipv6,udt}
@attribute Dir {'  <->','  <?>','   ->','   ?>','  who','  <-','  <?'}
@attribute State {CON,PA_PA,PA_FRA, ...}
@attribute sTos numeric
@attribute dTos numeric
@attribute TotPkts numeric
@attribute TotBytes numeric
@attribute SrcBytes numeric
@attribute class {Background,Normal,Botnet}

@data

1065.731934,udp,'  <->',CON,0,0,2,252,145,Background
1471.787109,udp,'  <->',CON,0,0,2,252,145,Background
...

#### Error Output
Command line string =  PrequentialEvaluation -l com.yahoo.labs.samoa.learners.classifiers.trees.VerticalHoeffdingTree -s (ArffFileStream -f test.arff) -f 1
2015-04-23 12:05:45,277 [main] INFO  com.yahoo.labs.samoa.LocalDoTask (LocalDoTask.java:80) - Successfully instantiating com.yahoo.labs.samoa.tasks.PrequentialEvaluation
Exception in thread "main" java.lang.NumberFormatException: For input string: "Background"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
	at java.lang.Double.valueOf(Double.java:504)
	at com.yahoo.labs.samoa.instances.ArffLoader.readInstanceDense(ArffLoader.java:105)
	at com.yahoo.labs.samoa.instances.ArffLoader.readInstance(ArffLoader.java:77)
	at com.yahoo.labs.samoa.instances.Instances.readInstance(Instances.java:182)
	at com.yahoo.labs.samoa.moa.streams.ArffFileStream.getNextInstanceFromFile(ArffFileStream.java:183)
	at com.yahoo.labs.samoa.moa.streams.ArffFileStream.readNextInstanceFromFile(ArffFileStream.java:145)
	at com.yahoo.labs.samoa.moa.streams.ArffFileStream.nextInstance(ArffFileStream.java:118)
	at com.yahoo.labs.samoa.moa.streams.ArffFileStream.nextInstance(ArffFileStream.java:46)
	at com.yahoo.labs.samoa.streams.StreamSource.nextInstance(StreamSource.java:70)
	at com.yahoo.labs.samoa.streams.PrequentialSourceProcessor.initStreamSource(PrequentialSourceProcessor.java:197)
	at com.yahoo.labs.samoa.streams.PrequentialSourceProcessor.getDataset(PrequentialSourceProcessor.java:170)
	at com.yahoo.labs.samoa.tasks.PrequentialEvaluation.init(PrequentialEvaluation.java:161)
	at com.yahoo.labs.samoa.LocalDoTask.main(LocalDoTask.java:87)

**Comment by gdfm** [comment]
Hi,
Thanks for reporting this bug.
I would encourage you to continue this discussion on the official Apache repository for SAMOA.
http://github.com/apache/incubator-samoa
As stated on the main page, this repository has been discontinued and will no longer be supported.
